---
- name: Terminate an EC2 instance
  hosts: localhost
  connection: local
  vars:
    instance_name: Ansible_EC2
  gather_facts: False
  tasks:
    - name: Gather EC2 instances information
      ec2_instance_info:
       region: us-east-1
       filters:
        "tag:Name": "{{ instance_name }}"
      register: ec2_info

    # - name: Extract instance IDs
    #    set_fact:
    #     instance_ids: "{{ ec2_info.instances | (attribute='instance_id') | list }}"

    - name: Terminate EC2 instance
      ec2_instance:
       instance_ids: "{{ ec2_info.instances[0].instance_id }}"
       region: us-east-1 
       state: absent
      register: termination