---
- name: Start an EC2 instance and associate an EIP
  hosts: localhost
  gather_facts: no
  vars:
    instance_ami: ami-09e617c6742d7ee13  # Replace with your AMI ID
    instance_type: t2.micro
    key_name: stackdevopsmanaut                  # Replace with your key pair name
    security_group_id: sg-0fc7e93a93422ffdf  # Replace with your security group ID
    subnet_id: subnet-05f502f802ae3158d # Replace with your subnet ID
    region: us-east-1                   # Replace with your desired region

  tasks:
    - name: Start EC2 instance
      amazon.aws.ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ instance_ami }}"
        wait: yes
        count: 1
        instance_tags:
          Name: AnsibleLaunchedInstance
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ security_group_id }}"
        region: "{{ region }}"
      register: ec2


    - name: Done
      debug:
        msg: "The instance is ready "
