---
- name: Start an EC2 instance and associate an EIP
  hosts: localhost
  connection: local
  become: False
  vars:
    instance_ami: ami-09e617c6742d7ee13  # Replace with your AMI ID
    instance_type: t2.micro
    key_name: stackdevopsmanaut                  # Replace with your key pair name
    security_group_id: sg-0fc7e93a93422ffdf  # Replace with your security group ID
    subnet_id: subnet-05f502f802ae3158d # Replace with your subnet ID
    region: us-east-1                   # Replace with your desired region

  tasks:
    - name: Start EC2 instance
      local_action:
        module: ec2_instance
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ instance_ami }}"
        wait: yes
        # count: 1
        wait_timeout: 1200
        # vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group_id }}"
        region: "{{ region }}"

    # - name: Wait for SSH to be available
    #   wait_for:
    #     host: "{{ ec2.instances[0].public_ip }}"
    #     port: 22
    #     delay: 30
    #     timeout: 300
    #     state: started

    # - name: Print instance public IP
    #   debug:
    #     msg: "The instance public IP is {{ ec2.instances[0].public_ip }}"
